import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {

	const codeBlockOne = `@container wp-block-quote (min-width: 500px) {
		background-color: #f00;
	}

	.second-class {
		padding: 0;
	}`;

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<div>
					<pre>
						<code
							className="language-css"
							dangerouslySetInnerHTML={{
								__html: codeBlockOne,
							}}
						/>
					</pre>
				</div>
			</main>
		</>
	);
}
